version: "3.3"
services:
  node:
    # build: ..
    image: ggpoc2/halborn:1.0.0
    container_name: halbornd
    ports:
      - "26657:26657"
    volumes:
      - ./genesis:/root/.halbornd
    command: halbornd start

  lcd:
    # build: ..
    image: ggpoc2/halborn:1.0.0
    container_name: light-client-daemon
    expose:
      - "1317"
    links:
      - node
    command: halborncli rest-server --laddr tcp://0.0.0.0:1317 --node tcp://node:26657 --trust-node=true
    depends_on:
      - node

  api:
    build: playground
    container_name: playground-api
    expose:
      - "5000"
    links:
      - lcd
    depends_on:
      - lcd

  web:
    build: playground/web
    container_name: playground-web
    ports:
      - "80:80"
    links:
      - api
    env_file:
      - ./playground/.env
    volumes:
      - ./playground/nginx:/etc/nginx/templates
    depends_on:
      - api
